# VNext layer override
# Use: docker-compose -f docker-compose.yml -f docker-compose.vnext.yml up

services:
  nginx:
    env_file:
      - global-components.vnext.mock.env
    volumes:
      - ../config/global-components.vnext/global-components.vnext.conf:/etc/nginx/templates/global-components.vnext.conf.template:ro
      - ../dist/global-components.vnext.js:/etc/nginx/templates/global-components.vnext.js:ro
