# Global-components layer override
# Use: docker-compose -f docker-compose.yml -f docker-compose.global-components.yml up

services:
  nginx:
    env_file:
      - global-components.mock.env
    volumes:
      - ../dist/global-components.conf.template:/etc/nginx/templates/global-components.conf.template:ro
      - ../dist/global-components.js:/etc/nginx/templates/global-components.js:ro
      - ./global-components-deployment.mock.json:/etc/nginx/templates/global-components-deployment.json:ro
